version: "3.4"
services:
  python:
    build: 
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - $(AUTOCHAMBER_DIR):/data/AC_Oulanka:ro
      - $(EDDY_DIR):/data/EC_Oulanka:ro
    entrypoint:
      ["/run.sh"]
